#!/usr/bin/env bash

# ──────────────────────────────────────────────────────────
# ctl.sh  —  generate management ctl.sh for the deployment
# ──────────────────────────────────────────────────────────

write_ctl_script() {
  local target_dir="${1:-$DEPLOY_DIR}"
  local ctl_file="$target_dir/ctl.sh"

  cat > "$ctl_file" <<'CTL_EOF'
#!/usr/bin/env bash
set -euo pipefail

# ── 微服务平台管理脚本 ──
# Auto-generated by the stage2 installer.

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"
ENV_FILE="$DEPLOY_DIR/.env"

# Detect docker compose command.
if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "ERROR: docker compose not found" >&2
  exit 1
fi

compose() { (cd "$DEPLOY_DIR" && "${DC[@]}" -f "$COMPOSE_FILE" "$@"); }

usage() {
  cat <<'USAGE'
Usage: bash ctl.sh <command> [options]

Commands:
  status          Show container status (docker compose ps)
  ps              Alias for status
  logs <svc>      Tail logs for a service (default: last 100 lines)
  restart         Restart all services
  start           Start all services
  stop            Stop all services
  health          Quick health overview
  report          Generate a deployment report
  update-images <path>
                  Load a new image package and recreate changed monitor-* services
  rollback        Show recent image tags for rollback
  help            Show this help
USAGE
}

cmd_status() {
  compose ps -a
}

cmd_logs() {
  local svc="${1:-}"
  local lines="${2:-100}"
  if [[ -z "$svc" ]]; then
    compose logs --tail="$lines"
  else
    compose logs --tail="$lines" -f "$svc"
  fi
}

cmd_restart() {
  echo "Restarting all services..."
  compose restart
}

cmd_start() {
  compose up -d
}

cmd_stop() {
  compose stop
}

cmd_health() {
  echo "═══════ Container Health ═══════"
  docker ps -a --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' \
    --filter "label=com.docker.compose.project" 2>/dev/null || \
    docker ps -a --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
  echo
  echo "═══════ Port Listening ═══════"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | head -30
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn 2>/dev/null | head -30
  else
    echo "ss/netstat not available"
  fi
}

cmd_report() {
  local report_dir="$DEPLOY_DIR/report"
  mkdir -p "$report_dir"
  local rf="$report_dir/ctl-report-$(date +%Y%m%d-%H%M%S).txt"
  {
    echo "Deployment status report"
    echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo
    echo "[Containers]"
    docker ps -a --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null
    echo
    echo "[Disk usage]"
    df -h "$DEPLOY_DIR" 2>/dev/null || df -h .
    echo
    echo "[Docker disk]"
    docker system df 2>/dev/null || echo "N/A"
  } > "$rf"
  echo "Report saved: $rf"
}

cmd_update_images() {
  local package_path="${1:-}"
  [[ -n "$package_path" ]] || {
    echo "ERROR: update-images requires a package path" >&2
    exit 1
  }
  [[ -e "$package_path" ]] || {
    echo "ERROR: image package path does not exist: $package_path" >&2
    exit 1
  }
  [[ -f "$DEPLOY_DIR/stage2/install.sh" ]] || {
    echo "ERROR: stage2 installer not found: $DEPLOY_DIR/stage2/install.sh" >&2
    exit 1
  }

  local config_args=()
  if [[ -f "$DEPLOY_DIR/deploy.conf" ]]; then
    config_args=(--config "$DEPLOY_DIR/deploy.conf")
  fi
  bash "$DEPLOY_DIR/stage2/install.sh" "${config_args[@]}" --update-images "$package_path" --yes
}

cmd_rollback() {
  echo "Recent images (use docker tag to rollback):"
  docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.CreatedAt}}' | head -30
}

# ── main ──
case "${1:-help}" in
  status|ps)    cmd_status ;;
  logs)         shift; cmd_logs "$@" ;;
  restart)      cmd_restart ;;
  start)        cmd_start ;;
  stop)         cmd_stop ;;
  health)       cmd_health ;;
  report)       cmd_report ;;
  update-images) shift; cmd_update_images "$@" ;;
  rollback)     cmd_rollback ;;
  help|-h|--help) usage ;;
  *)            echo "Unknown command: $1" >&2; usage; exit 1 ;;
esac
CTL_EOF

  chmod +x "$ctl_file"
  log_success "management script generated: $ctl_file"
}
