#!/usr/bin/env bash

set_stage2_defaults() {
  CONTENT_MYSQL_IP_PORT_EXPLICIT="${CONTENT_MYSQL_IP_PORT+x}"
  CONTENT_REDIS_HOST_EXPLICIT="${CONTENT_REDIS_HOST+x}"
  CONTENT_REDIS_PORT_EXPLICIT="${CONTENT_REDIS_PORT+x}"
  CONTENT_NACOS_IP_PORT_EXPLICIT="${CONTENT_NACOS_IP_PORT+x}"
  CONTENT_MINIO_ENDPOINT_EXPLICIT="${CONTENT_MINIO_ENDPOINT+x}"
  CONTENT_MONITOR_RULE_URL_EXPLICIT="${CONTENT_MONITOR_RULE_URL+x}"
  CONTENT_MONITOR_ALARM_URL_EXPLICIT="${CONTENT_MONITOR_ALARM_URL+x}"
  CONTENT_MONITOR_DEVICE_URL_EXPLICIT="${CONTENT_MONITOR_DEVICE_URL+x}"
  CONTENT_MONITOR_FORWARD_URL_EXPLICIT="${CONTENT_MONITOR_FORWARD_URL+x}"
  MONITOR_CONTENT_URL_EXPLICIT="${MONITOR_CONTENT_URL+x}"

  MIN_CPU_CORES="${MIN_CPU_CORES:-4}"
  MIN_MEMORY_MB="${MIN_MEMORY_MB:-8192}"
  MIN_DISK_GB="${MIN_DISK_GB:-50}"

  MYSQL_HOST="${MYSQL_HOST:-db}"
  MYSQL_PORT="${MYSQL_PORT:-3306}"
  MYSQL_HOST_PORT="${MYSQL_HOST_PORT:-23306}"
  MYSQL_DB="${MYSQL_DB:-monitor_platform}"
  MYSQL_USER="${MYSQL_USER:-${MYSQL_USERNAME:-}}"
  MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-${MYSQL_PASSWORD:-}}"

  REDIS_HOST="${REDIS_HOST:-redis}"
  REDIS_PORT="${REDIS_PORT:-6379}"
  REDIS_HOST_PORT="${REDIS_HOST_PORT:-26379}"

  NACOS_HOST="${NACOS_HOST:-nacos}"
  NACOS_PORT="${NACOS_PORT:-8848}"
  NACOS_HOST_PORT="${NACOS_HOST_PORT:-18848}"
  NACOS_GRPC_PORT="${NACOS_GRPC_PORT:-19848}"
  NACOS_RAFT_PORT="${NACOS_RAFT_PORT:-19849}"
  NACOS_NAMESPACE="${NACOS_NAMESPACE:-5c87647a-8a17-4adb-94ce-04047ea26d96}"

  SENTINEL_HOST="${SENTINEL_HOST:-127.0.0.1}"
  SENTINEL_PORT="${SENTINEL_PORT:-8858}"

  DISPATCH_MODE="${DISPATCH_MODE:-http}"
  MQTT_BROKER_URL="${MQTT_BROKER_URL:-ssl://127.0.0.1:8883}"
  MQTT_USERNAME="${MQTT_USERNAME:-}"
  MQTT_PASSWORD="${MQTT_PASSWORD:-}"
  MQTT_TENANT_ID="${MQTT_TENANT_ID:-default}"
  MQTT_SITE_ID="${MQTT_SITE_ID:-site-001}"
  MQTT_PLATFORM_CLIENT_ID="${MQTT_PLATFORM_CLIENT_ID:-monitor-platform-001}"
  MQTT_RECONNECT_INTERVAL_MS="${MQTT_RECONNECT_INTERVAL_MS:-30000}"
  UPGRADE_DOWNLOAD_BASE_URL="${UPGRADE_DOWNLOAD_BASE_URL:-}"

  MINIO_API_PORT="${MINIO_API_PORT:-19000}"
  MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-19002}"
  MINIO_ENDPOINT="${MINIO_ENDPOINT:-http://minio:9000}"
  MINIO_BUCKET="${MINIO_BUCKET:-monitor-platform}"

  UKEY_SETUP_MODE="${UKEY_SETUP_MODE:-deferred}"
  VAUTH_SERVER_MODE="${VAUTH_SERVER_MODE:-ukey}"
  VAUTH_SERVER_PASSWORD="${VAUTH_SERVER_PASSWORD:-}"
  VAUTH_SERVER_AUTH_ID="${VAUTH_SERVER_AUTH_ID:-}"

  GATEWAY_PORT="${GATEWAY_PORT:-8060}"
  DEVICE_PORT="${DEVICE_PORT:-8062}"
  UKEY_PORT="${UKEY_PORT:-8063}"
  ALARM_PORT="${ALARM_PORT:-8064}"
  CONTENT_PORT="${CONTENT_PORT:-8065}"
  RULE_PORT="${RULE_PORT:-8066}"
  FORWARD_PORT="${FORWARD_PORT:-8067}"
  ROLE_PORT="${ROLE_PORT:-8068}"
  REGISTRY_PORT="${REGISTRY_PORT:-8069}"
  WEBSOCKET_PORT="${WEBSOCKET_PORT:-8070}"
  LOG_PORT="${LOG_PORT:-8071}"
  NGINX_PORT="${NGINX_PORT:-80}"
  NGINX_SSL_PORT="${NGINX_SSL_PORT:-443}"
  EMQX_MQTT_PORT="${EMQX_MQTT_PORT:-1883}"
  EMQX_MQTTS_PORT="${EMQX_MQTTS_PORT:-8883}"
  EMQX_DASHBOARD_PORT="${EMQX_DASHBOARD_PORT:-18083}"

  CONTENT_MYSQL_IP_PORT="${CONTENT_MYSQL_IP_PORT:-127.0.0.1:${MYSQL_HOST_PORT}}"
  CONTENT_REDIS_HOST="${CONTENT_REDIS_HOST:-127.0.0.1}"
  CONTENT_REDIS_PORT="${CONTENT_REDIS_PORT:-${REDIS_HOST_PORT}}"
  CONTENT_NACOS_IP_PORT="${CONTENT_NACOS_IP_PORT:-127.0.0.1:${NACOS_HOST_PORT}}"
  CONTENT_MINIO_ENDPOINT="${CONTENT_MINIO_ENDPOINT:-http://127.0.0.1:${MINIO_API_PORT}}"

  CONTENT_MONITOR_RULE_URL="${CONTENT_MONITOR_RULE_URL:-http://127.0.0.1:${RULE_PORT}}"
  CONTENT_MONITOR_ALARM_URL="${CONTENT_MONITOR_ALARM_URL:-http://127.0.0.1:${ALARM_PORT}}"
  CONTENT_MONITOR_DEVICE_URL="${CONTENT_MONITOR_DEVICE_URL:-http://127.0.0.1:${DEVICE_PORT}}"
  CONTENT_MONITOR_FORWARD_URL="${CONTENT_MONITOR_FORWARD_URL:-http://127.0.0.1:${FORWARD_PORT}}"

  MONITOR_DEVICE_URL="${MONITOR_DEVICE_URL:-http://monitor-device:8062}"
  MONITOR_LOG_URL="${MONITOR_LOG_URL:-http://monitor-log:8071}"
  MONITOR_CONTENT_URL="${MONITOR_CONTENT_URL:-http://host.docker.internal:${CONTENT_PORT}}"

  AUDIT_MODE="${AUDIT_MODE:-local}"
  LOCAL_AUDIT_IMAGE_URL="${LOCAL_AUDIT_IMAGE_URL:-http://127.0.0.1:21580/api/audit/image/quick}"
  LOCAL_AUDIT_TEXT_URL="${LOCAL_AUDIT_TEXT_URL:-http://127.0.0.1:21580/api/audit/text}"
  LOCAL_AUDIT_VIDEO_URL="${LOCAL_AUDIT_VIDEO_URL:-http://127.0.0.1:21580/api/audit/video/quick}"
  LOCAL_AUDIT_VIDEO_FRAME_INTERVAL="${LOCAL_AUDIT_VIDEO_FRAME_INTERVAL:-0.5}"
  LOCAL_AUDIT_VIDEO_MAX_FRAMES="${LOCAL_AUDIT_VIDEO_MAX_FRAMES:-200}"
  LOCAL_AUDIT_VIDEO_SAVE_FRAMES="${LOCAL_AUDIT_VIDEO_SAVE_FRAMES:-false}"
  LOCAL_AUDIT_AUTH_MODE="${LOCAL_AUDIT_AUTH_MODE:-none}"
  LOCAL_AUDIT_AUTH_URL="${LOCAL_AUDIT_AUTH_URL:-}"
  LOCAL_AUDIT_AUTH_USERNAME="${LOCAL_AUDIT_AUTH_USERNAME:-admin}"
  LOCAL_AUDIT_AUTH_PASSWORD="${LOCAL_AUDIT_AUTH_PASSWORD:-}"
  LOCAL_AUDIT_AUTH_CERT_PATH="${LOCAL_AUDIT_AUTH_CERT_PATH:-}"
  LOCAL_AUDIT_AUTH_TOKEN="${LOCAL_AUDIT_AUTH_TOKEN:-}"
  CONTENT_JMDNS_BIND_ADDRESS="${CONTENT_JMDNS_BIND_ADDRESS:-}"

  LOG_REPORT_TOKEN="${LOG_REPORT_TOKEN:-}"
  LOG_RETENTION_DAYS="${LOG_RETENTION_DAYS:-90}"
  LOG_DEDUP_WINDOW_SECONDS="${LOG_DEDUP_WINDOW_SECONDS:-60}"

  HEALTH_RETRIES="${HEALTH_RETRIES:-40}"
  HEALTH_INTERVAL_SECONDS="${HEALTH_INTERVAL_SECONDS:-5}"
  PULL_PUBLIC_IMAGES="${PULL_PUBLIC_IMAGES:-true}"
  AUTO_OPEN_FIREWALL="${AUTO_OPEN_FIREWALL:-true}"
  AUTO_INSTALL_DOCKER="${AUTO_INSTALL_DOCKER:-false}"

  sync_stage2_derived_config
}

sync_stage2_derived_config() {
  [[ "${CONTENT_MYSQL_IP_PORT_EXPLICIT:-}" == "x" ]] || CONTENT_MYSQL_IP_PORT="127.0.0.1:${MYSQL_HOST_PORT}"
  [[ "${CONTENT_REDIS_HOST_EXPLICIT:-}" == "x" ]] || CONTENT_REDIS_HOST="127.0.0.1"
  [[ "${CONTENT_REDIS_PORT_EXPLICIT:-}" == "x" ]] || CONTENT_REDIS_PORT="${REDIS_HOST_PORT}"
  [[ "${CONTENT_NACOS_IP_PORT_EXPLICIT:-}" == "x" ]] || CONTENT_NACOS_IP_PORT="127.0.0.1:${NACOS_HOST_PORT}"
  [[ "${CONTENT_MINIO_ENDPOINT_EXPLICIT:-}" == "x" ]] || CONTENT_MINIO_ENDPOINT="http://127.0.0.1:${MINIO_API_PORT}"
  [[ "${CONTENT_MONITOR_RULE_URL_EXPLICIT:-}" == "x" ]] || CONTENT_MONITOR_RULE_URL="http://127.0.0.1:${RULE_PORT}"
  [[ "${CONTENT_MONITOR_ALARM_URL_EXPLICIT:-}" == "x" ]] || CONTENT_MONITOR_ALARM_URL="http://127.0.0.1:${ALARM_PORT}"
  [[ "${CONTENT_MONITOR_DEVICE_URL_EXPLICIT:-}" == "x" ]] || CONTENT_MONITOR_DEVICE_URL="http://127.0.0.1:${DEVICE_PORT}"
  [[ "${CONTENT_MONITOR_FORWARD_URL_EXPLICIT:-}" == "x" ]] || CONTENT_MONITOR_FORWARD_URL="http://127.0.0.1:${FORWARD_PORT}"
  [[ "${MONITOR_CONTENT_URL_EXPLICIT:-}" == "x" ]] || MONITOR_CONTENT_URL="http://host.docker.internal:${CONTENT_PORT}"
}

load_stage2_config() {
  [[ -f "$CONFIG_FILE" ]] || fail "deploy config not found: $CONFIG_FILE"
  # Existing deploy.conf is a shell-style config file.
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  set_stage2_defaults
}

require_value() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "$value" ]] || fail "missing required config: $name"
}

validate_password_value() {
  local name="$1"
  local value="${!name:-}"
  [[ -n "$value" ]] || return
  if (( ${#value} < 8 )); then
    fail "$name must be at least 8 characters"
  fi
  if [[ "$value" =~ (123456|admin123456|root123456|password|PASSWORD|YOUR_|_HERE|CHANGE_ME|TODO|Replace_) ]]; then
    fail "$name looks like a weak password or placeholder"
  fi
}

validate_account_name() {
  local name="$1"
  local value="${!name:-}"
  local lower_value
  lower_value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  case "$lower_value" in
    root|admin|guest|test|user|administrator|default|anonymous)
      fail "$name uses forbidden account name: $value"
      ;;
  esac
}

validate_stage2_config() {
  local required=(
    MYSQL_PASSWORD MYSQL_ROOT_PASSWORD MYSQL_USER
    REDIS_PASSWORD
    MINIO_ROOT_USER MINIO_ROOT_PASSWORD MINIO_ACCESS_KEY MINIO_SECRET_KEY
    UKEY_ADMIN_USERNAME UKEY_ADMIN_PASSWORD
    UPGRADE_DOWNLOAD_BASE_URL
  )
  local name
  for name in "${required[@]}"; do
    require_value "$name"
  done

  [[ "$MYSQL_HOST" == "db" ]] || fail "stage2 single-node requires MYSQL_HOST=db, got: $MYSQL_HOST"
  [[ "$MYSQL_PORT" == "3306" ]] || fail "stage2 single-node requires MYSQL_PORT=3306, got: $MYSQL_PORT"
  [[ "$REDIS_HOST" == "redis" ]] || fail "stage2 single-node requires REDIS_HOST=redis, got: $REDIS_HOST"
  [[ "$REDIS_PORT" == "6379" ]] || fail "stage2 single-node requires REDIS_PORT=6379, got: $REDIS_PORT"
  [[ "$NACOS_HOST" == "nacos" ]] || fail "stage2 single-node requires NACOS_HOST=nacos, got: $NACOS_HOST"
  [[ "$NACOS_PORT" == "8848" ]] || fail "stage2 single-node requires NACOS_PORT=8848, got: $NACOS_PORT"
  [[ "$MINIO_ENDPOINT" == "http://minio:9000" ]] || fail "stage2 single-node requires MINIO_ENDPOINT=http://minio:9000, got: $MINIO_ENDPOINT"
  [[ "$VAUTH_SERVER_MODE" == "ukey" || "$VAUTH_SERVER_MODE" == "sdf" ]] || fail "VAUTH_SERVER_MODE must be ukey or sdf, got: $VAUTH_SERVER_MODE"
  [[ "$UKEY_SETUP_MODE" == "required" || "$UKEY_SETUP_MODE" == "deferred" ]] || fail "UKEY_SETUP_MODE must be required or deferred, got: $UKEY_SETUP_MODE"
  [[ "$DISPATCH_MODE" == "http" || "$DISPATCH_MODE" == "mqtt" || "$DISPATCH_MODE" == "dual" ]] || fail "DISPATCH_MODE must be http, mqtt or dual, got: $DISPATCH_MODE"
  [[ "$MQTT_RECONNECT_INTERVAL_MS" =~ ^[0-9]+$ ]] || fail "MQTT_RECONNECT_INTERVAL_MS must be numeric: $MQTT_RECONNECT_INTERVAL_MS"
  [[ "$UPGRADE_DOWNLOAD_BASE_URL" =~ ^https?:// ]] || fail "UPGRADE_DOWNLOAD_BASE_URL must start with http:// or https://"
  [[ "$UPGRADE_DOWNLOAD_BASE_URL" != *"YOUR_PUBLIC_PLATFORM_HOST"* ]] || fail "UPGRADE_DOWNLOAD_BASE_URL must be replaced with the public platform address"

  if [[ "$DISPATCH_MODE" == "mqtt" || "$DISPATCH_MODE" == "dual" ]]; then
    require_value MQTT_BROKER_URL
  fi

  validate_account_name MYSQL_USER
  validate_account_name MINIO_ROOT_USER
  validate_account_name MINIO_ACCESS_KEY
  validate_account_name UKEY_ADMIN_USERNAME
  [[ "$MYSQL_USER" =~ ^[A-Za-z0-9_][A-Za-z0-9_-]{2,31}$ ]] || fail "MYSQL_USER must match ^[A-Za-z0-9_][A-Za-z0-9_-]{2,31}$"

  for name in MYSQL_PASSWORD MYSQL_ROOT_PASSWORD REDIS_PASSWORD MINIO_ROOT_PASSWORD MINIO_SECRET_KEY UKEY_ADMIN_PASSWORD; do
    validate_password_value "$name"
  done

  if [[ "$UKEY_SETUP_MODE" == "required" ]]; then
    require_value VAUTH_SERVER_PASSWORD
    require_value VAUTH_SERVER_AUTH_ID
    validate_password_value VAUTH_SERVER_PASSWORD
  elif [[ -n "${VAUTH_SERVER_PASSWORD:-}" ]]; then
    validate_password_value VAUTH_SERVER_PASSWORD
  fi

  local port_vars=(
    MYSQL_PORT MYSQL_HOST_PORT REDIS_PORT REDIS_HOST_PORT
    NACOS_PORT NACOS_HOST_PORT NACOS_GRPC_PORT NACOS_RAFT_PORT
    MINIO_API_PORT MINIO_CONSOLE_PORT
    GATEWAY_PORT DEVICE_PORT UKEY_PORT ALARM_PORT CONTENT_PORT RULE_PORT FORWARD_PORT ROLE_PORT REGISTRY_PORT
    WEBSOCKET_PORT LOG_PORT NGINX_PORT NGINX_SSL_PORT
    EMQX_MQTT_PORT EMQX_MQTTS_PORT EMQX_DASHBOARD_PORT
  )
  for name in "${port_vars[@]}"; do
    is_port "${!name}" || fail "$name is not a valid port: ${!name}"
  done
}

stage2_host_ports() {
  dedupe_ports \
    "$MYSQL_HOST_PORT" "$REDIS_HOST_PORT" "$NACOS_HOST_PORT" "$NACOS_GRPC_PORT" "$NACOS_RAFT_PORT" \
    "$MINIO_API_PORT" "$MINIO_CONSOLE_PORT" \
    "$GATEWAY_PORT" "$DEVICE_PORT" "$UKEY_PORT" "$ALARM_PORT" "$CONTENT_PORT" "$RULE_PORT" \
    "$FORWARD_PORT" "$ROLE_PORT" "$REGISTRY_PORT" "$WEBSOCKET_PORT" "$LOG_PORT" "$NGINX_PORT" "$NGINX_SSL_PORT" \
    "$EMQX_MQTT_PORT" "$EMQX_MQTTS_PORT" "$EMQX_DASHBOARD_PORT"
}

write_stage2_env() {
  log_info "rendering compose env: $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
MYSQL_IP_PORT=${MYSQL_HOST}:${MYSQL_PORT}
MYSQL_USERNAME=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_HOST_PORT=${MYSQL_HOST_PORT}
MYSQL_DB=${MYSQL_DB}
SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_HOST_PORT=${REDIS_HOST_PORT}
SPRING_REDIS_HOST=${REDIS_HOST}
SPRING_REDIS_PORT=${REDIS_PORT}
SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
SPRING_REDIS_DATABASE=0

NACOS_IP_PORT=${NACOS_HOST}:${NACOS_PORT}
NACOS_NAMESPACE=${NACOS_NAMESPACE}
NACOS_HOST_PORT=${NACOS_HOST_PORT}
NACOS_GRPC_PORT=${NACOS_GRPC_PORT}
NACOS_RAFT_PORT=${NACOS_RAFT_PORT}

SENTINEL_IP_PORT=${SENTINEL_HOST}:${SENTINEL_PORT}
SENTINEL_PORT=${SENTINEL_PORT}

MINIO_ENDPOINT=${MINIO_ENDPOINT}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET_NAME=${MINIO_BUCKET}
MINIO_API_PORT=${MINIO_API_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}

CONTENT_MYSQL_IP_PORT=${CONTENT_MYSQL_IP_PORT}
CONTENT_REDIS_HOST=${CONTENT_REDIS_HOST}
CONTENT_REDIS_PORT=${CONTENT_REDIS_PORT}
CONTENT_NACOS_IP_PORT=${CONTENT_NACOS_IP_PORT}
CONTENT_MINIO_ENDPOINT=${CONTENT_MINIO_ENDPOINT}
CONTENT_MONITOR_RULE_URL=${CONTENT_MONITOR_RULE_URL}
CONTENT_MONITOR_ALARM_URL=${CONTENT_MONITOR_ALARM_URL}
CONTENT_MONITOR_DEVICE_URL=${CONTENT_MONITOR_DEVICE_URL}
CONTENT_MONITOR_FORWARD_URL=${CONTENT_MONITOR_FORWARD_URL}
CONTENT_JMDNS_BIND_ADDRESS=${CONTENT_JMDNS_BIND_ADDRESS}

UKEY_ADMIN_USERNAME=${UKEY_ADMIN_USERNAME}
UKEY_ADMIN_PASSWORD=${UKEY_ADMIN_PASSWORD}
UKEY_SETUP_MODE=${UKEY_SETUP_MODE}
VAUTH_SERVER_MODE=${VAUTH_SERVER_MODE}
VAUTH_SERVER_PASSWORD=${VAUTH_SERVER_PASSWORD}
VAUTH_SERVER_AUTH_ID=${VAUTH_SERVER_AUTH_ID}

MONITOR_DEVICE_URL=${MONITOR_DEVICE_URL}
MONITOR_LOG_URL=${MONITOR_LOG_URL}
MONITOR_CONTENT_URL=${MONITOR_CONTENT_URL}
LOG_REPORT_TOKEN=${LOG_REPORT_TOKEN}
LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS}
LOG_DEDUP_WINDOW_SECONDS=${LOG_DEDUP_WINDOW_SECONDS}

DISPATCH_MODE=${DISPATCH_MODE}
MQTT_BROKER_URL=${MQTT_BROKER_URL}
MQTT_USERNAME=${MQTT_USERNAME}
MQTT_PASSWORD=${MQTT_PASSWORD}
MQTT_TENANT_ID=${MQTT_TENANT_ID}
MQTT_SITE_ID=${MQTT_SITE_ID}
MQTT_PLATFORM_CLIENT_ID=${MQTT_PLATFORM_CLIENT_ID}
MQTT_RECONNECT_INTERVAL_MS=${MQTT_RECONNECT_INTERVAL_MS}
UPGRADE_DOWNLOAD_BASE_URL=${UPGRADE_DOWNLOAD_BASE_URL}

AUDIT_MODE=${AUDIT_MODE}
LOCAL_AUDIT_IMAGE_URL=${LOCAL_AUDIT_IMAGE_URL}
LOCAL_AUDIT_TEXT_URL=${LOCAL_AUDIT_TEXT_URL}
LOCAL_AUDIT_VIDEO_URL=${LOCAL_AUDIT_VIDEO_URL}
LOCAL_AUDIT_VIDEO_FRAME_INTERVAL=${LOCAL_AUDIT_VIDEO_FRAME_INTERVAL}
LOCAL_AUDIT_VIDEO_MAX_FRAMES=${LOCAL_AUDIT_VIDEO_MAX_FRAMES}
LOCAL_AUDIT_VIDEO_SAVE_FRAMES=${LOCAL_AUDIT_VIDEO_SAVE_FRAMES}
LOCAL_AUDIT_AUTH_MODE=${LOCAL_AUDIT_AUTH_MODE}
LOCAL_AUDIT_AUTH_URL=${LOCAL_AUDIT_AUTH_URL}
LOCAL_AUDIT_AUTH_USERNAME=${LOCAL_AUDIT_AUTH_USERNAME}
LOCAL_AUDIT_AUTH_PASSWORD=${LOCAL_AUDIT_AUTH_PASSWORD}
LOCAL_AUDIT_AUTH_CERT_PATH=${LOCAL_AUDIT_AUTH_CERT_PATH}
LOCAL_AUDIT_AUTH_TOKEN=${LOCAL_AUDIT_AUTH_TOKEN}

GATEWAY_PORT=${GATEWAY_PORT}
DEVICE_PORT=${DEVICE_PORT}
UKEY_PORT=${UKEY_PORT}
ALARM_PORT=${ALARM_PORT}
CONTENT_PORT=${CONTENT_PORT}
RULE_PORT=${RULE_PORT}
FORWARD_PORT=${FORWARD_PORT}
ROLE_PORT=${ROLE_PORT}
REGISTRY_PORT=${REGISTRY_PORT}
WEBSOCKET_PORT=${WEBSOCKET_PORT}
LOG_PORT=${LOG_PORT}
NGINX_PORT=${NGINX_PORT}
NGINX_SSL_PORT=${NGINX_SSL_PORT}
EMQX_MQTT_PORT=${EMQX_MQTT_PORT}
EMQX_MQTTS_PORT=${EMQX_MQTTS_PORT}
EMQX_DASHBOARD_PORT=${EMQX_DASHBOARD_PORT}
EOF
  chmod 600 "$ENV_FILE"
}
