package com.monitorplatform.common.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;

/**
 * AES-GCM encryption/decryption utility for sensitive data transport.
 */
public class EncryptUtil {

    private static final Logger log = LoggerFactory.getLogger(EncryptUtil.class);

    private static final String ALGORITHM = "AES";

    private static final String TRANSFORMATION = "AES/GCM/NoPadding";

    private static final int KEY_LENGTH = 32;

    private static final int IV_LENGTH = 12;

    private static final int TAG_LENGTH_BIT = 128;

    private static final int TAG_LENGTH_BYTE = TAG_LENGTH_BIT / 8;

    /**
     * Encrypt plain text and return Base64([12-byte IV] + [cipher text + GCM tag]).
     *
     * @param data plain text
     * @param key AES key. Prefer Base64-encoded 32-byte key generated by generateKey().
     * @return Base64 encoded encrypted data
     */
    public static String encrypt(String data, String key) {
        try {
            byte[] iv = new byte[IV_LENGTH];
            SecureRandom secureRandom = new SecureRandom();
            secureRandom.nextBytes(iv);

            byte[] keyBytes = getKeyBytes(key);
            SecretKeySpec keySpec = new SecretKeySpec(keyBytes, ALGORITHM);

            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            GCMParameterSpec gcmParameterSpec = new GCMParameterSpec(TAG_LENGTH_BIT, iv);
            cipher.init(Cipher.ENCRYPT_MODE, keySpec, gcmParameterSpec);

            byte[] dataBytes = data.getBytes(StandardCharsets.UTF_8);
            byte[] cipherText = cipher.doFinal(dataBytes);

            ByteBuffer byteBuffer = ByteBuffer.allocate(IV_LENGTH + cipherText.length);
            byteBuffer.put(iv);
            byteBuffer.put(cipherText);

            return Base64.getEncoder().encodeToString(byteBuffer.array());
        } catch (Exception e) {
            log.error("AES encryption failed", e);
            throw new RuntimeException("Encryption failed", e);
        }
    }

    /**
     * Decrypt Base64([12-byte IV] + [cipher text + GCM tag]).
     *
     * @param encryptedData Base64 encoded encrypted data
     * @param key AES key. Prefer Base64-encoded 32-byte key generated by generateKey().
     * @return plain text
     */
    public static String decrypt(String encryptedData, String key) {
        try {
            byte[] decoded = Base64.getDecoder().decode(encryptedData);
            if (decoded.length < IV_LENGTH + TAG_LENGTH_BYTE) {
                throw new IllegalArgumentException("Invalid encrypted data length");
            }

            ByteBuffer byteBuffer = ByteBuffer.wrap(decoded);
            byte[] iv = new byte[IV_LENGTH];
            byteBuffer.get(iv);
            byte[] cipherText = new byte[byteBuffer.remaining()];
            byteBuffer.get(cipherText);

            Exception lastException = null;
            for (byte[] keyBytes : getDecryptKeyCandidates(key)) {
                try {
                    byte[] plainText = doDecrypt(cipherText, iv, keyBytes);
                    return new String(plainText, StandardCharsets.UTF_8);
                } catch (Exception e) {
                    lastException = e;
                }
            }
            if (lastException != null) {
                throw lastException;
            }
            throw new IllegalArgumentException("Invalid AES key");
        } catch (Exception e) {
            log.error("AES decryption failed", e);
            throw new RuntimeException("Decryption failed", e);
        }
    }

    /**
     * Generate a Base64-encoded 32-byte AES key.
     *
     * @return Base64 encoded AES key
     */
    public static String generateKey() {
        byte[] key = new byte[KEY_LENGTH];
        new SecureRandom().nextBytes(key);
        return Base64.getEncoder().encodeToString(key);
    }

    private static byte[] doDecrypt(byte[] cipherText, byte[] iv, byte[] keyBytes) throws Exception {
        SecretKeySpec keySpec = new SecretKeySpec(keyBytes, ALGORITHM);

        Cipher cipher = Cipher.getInstance(TRANSFORMATION);
        GCMParameterSpec gcmParameterSpec = new GCMParameterSpec(TAG_LENGTH_BIT, iv);
        cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmParameterSpec);

        return cipher.doFinal(cipherText);
    }

    private static List<byte[]> getDecryptKeyCandidates(String key) {
        List<byte[]> candidates = new ArrayList<>();
        byte[] preferredKey = getKeyBytes(key);
        candidates.add(preferredKey);

        byte[] legacyKey = getLegacyKeyBytes(key);
        if (!Arrays.equals(preferredKey, legacyKey)) {
            candidates.add(legacyKey);
        }
        return candidates;
    }

    private static byte[] getKeyBytes(String key) {
        if (key == null || key.trim().isEmpty()) {
            throw new IllegalArgumentException("AES key must not be empty");
        }

        byte[] base64KeyBytes = decodeBase64Key(key.trim());
        if (base64KeyBytes != null) {
            return base64KeyBytes;
        }

        return getLegacyKeyBytes(key);
    }

    private static byte[] decodeBase64Key(String key) {
        try {
            byte[] decodedKey = Base64.getDecoder().decode(key);
            return decodedKey.length == KEY_LENGTH ? decodedKey : null;
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    private static byte[] getLegacyKeyBytes(String key) {
        byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);

        if (keyBytes.length < KEY_LENGTH) {
            try {
                MessageDigest digest = MessageDigest.getInstance("SHA-256");
                keyBytes = digest.digest(keyBytes);
            } catch (Exception e) {
                throw new RuntimeException("AES key handling failed", e);
            }
        }

        if (keyBytes.length > KEY_LENGTH) {
            byte[] truncated = new byte[KEY_LENGTH];
            System.arraycopy(keyBytes, 0, truncated, 0, KEY_LENGTH);
            keyBytes = truncated;
        }

        return keyBytes;
    }
}
